package com.nexus.app.ui.screens.ai

import android.util.Log
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.nexus.app.data.local.TaskEntity
import com.nexus.app.data.remote.AIChatRequest
import com.nexus.app.data.remote.AIInsightTaskRequest
import com.nexus.app.data.remote.AIInsightsRequest
import com.nexus.app.data.remote.AIPlanRequest
import com.nexus.app.data.remote.ApiClient
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch

enum class AITab {
    CHAT,
    PLANNER,
    INSIGHTS
}

data class AIMessage(
    val text: String,
    val isUser: Boolean
)

data class AIPlanTask(
    val title: String,
    val time: String,
    val duration: String,
    val category: String
)

data class AIInsightCard(
    val title: String,
    val value: String,
    val description: String
)

class AIViewModel : ViewModel() {

    // =========================================================
    // TAB
    // =========================================================

    var selectedTab by mutableStateOf(AITab.CHAT)
        private set

    // =========================================================
    // CHAT
    // =========================================================

    var inputText by mutableStateOf("")
        private set

    var isLoading by mutableStateOf(false)
        private set

    var messages by mutableStateOf(
        listOf(
            AIMessage(
                text = "Hi! I'm Nexus AI. I can help you organize tasks, plan your day, and understand your productivity.",
                isUser = false
            )
        )
    )
        private set

    // =========================================================
    // PLANNER
    // =========================================================

    var plannerInput by mutableStateOf("")
        private set

    var generatedPlan by mutableStateOf<List<AIPlanTask>>(emptyList())
        private set

    var plannerGenerated by mutableStateOf(false)
        private set

    var plannerLoading by mutableStateOf(false)
        private set

    var plannerError by mutableStateOf<String?>(null)
        private set

    // =========================================================
    // INSIGHTS
    // =========================================================

    var insights by mutableStateOf<List<AIInsightCard>>(emptyList())
        private set

    var insightsLoading by mutableStateOf(false)
        private set

    var insightsError by mutableStateOf<String?>(null)
        private set

    private var insightsJob: Job? = null
    private var lastInsightsSignature: String? = null

    // =========================================================
    // BASIC
    // =========================================================

    fun selectTab(tab: AITab) {
        selectedTab = tab
    }

    fun updateInput(value: String) {
        inputText = value
    }

    fun updatePlannerInput(value: String) {
        plannerInput = value
        plannerError = null
    }

    // =========================================================
    // CHAT
    // =========================================================

    fun sendMessage() {

        val message = inputText.trim()

        if (message.isEmpty() || isLoading) {
            return
        }

        messages = messages + AIMessage(
            text = message,
            isUser = true
        )

        inputText = ""
        isLoading = true

        viewModelScope.launch {

            try {

                Log.d(
                    "NEXUS_AI",
                    "Sending message: $message"
                )

                val response = ApiClient.api.chatWithAI(
                    AIChatRequest(
                        message = message
                    )
                )

                Log.d(
                    "NEXUS_AI",
                    "HTTP CODE: ${response.code()}"
                )

                if (response.isSuccessful) {

                    val aiResponse =
                        response.body()?.response
                            ?: "Sorry, I couldn't generate a response."

                    messages = messages + AIMessage(
                        text = aiResponse,
                        isUser = false
                    )

                } else {

                    val errorBody =
                        response.errorBody()?.string()

                    Log.e(
                        "NEXUS_AI",
                        "API ERROR: ${response.code()} $errorBody"
                    )

                    messages = messages + AIMessage(
                        text = "NEXUS AI error (${response.code()}).",
                        isUser = false
                    )
                }

            } catch (e: Exception) {

                Log.e(
                    "NEXUS_AI",
                    "AI CHAT ERROR",
                    e
                )

                messages = messages + AIMessage(
                    text = "Unable to connect to NEXUS AI.",
                    isUser = false
                )

            } finally {

                isLoading = false
            }
        }
    }

    // =========================================================
    // REAL AI PLANNER
    // =========================================================

    fun generatePlan() {

        val request = plannerInput.trim()

        if (request.isEmpty() || plannerLoading) {
            return
        }

        plannerLoading = true
        plannerError = null
        plannerGenerated = false
        generatedPlan = emptyList()

        viewModelScope.launch {

            try {

                Log.d(
                    "NEXUS_AI",
                    "Generating AI planner for: $request"
                )

                val response = ApiClient.api.generateAIPlan(
                    AIPlanRequest(
                        goal = request
                    )
                )

                Log.d(
                    "NEXUS_AI",
                    "PLANNER HTTP CODE: ${response.code()}"
                )

                if (response.isSuccessful) {

                    val body = response.body()

                    if (body == null || body.tasks.isEmpty()) {

                        plannerError =
                            "Nexus AI tidak menghasilkan rencana."

                    } else {

                        generatedPlan = body.tasks.map { task ->

                            AIPlanTask(
                                title = task.title.trim(),
                                time = task.time.trim(),
                                duration = task.duration.trim(),
                                category = task.category.trim()
                            )
                        }

                        plannerGenerated = true

                        Log.d(
                            "NEXUS_AI",
                            "Planner generated ${generatedPlan.size} tasks"
                        )
                    }

                } else {

                    val errorBody =
                        response.errorBody()?.string()

                    Log.e(
                        "NEXUS_AI",
                        "PLANNER ERROR: ${response.code()} $errorBody"
                    )

                    plannerError =
                        "AI Planner gagal (${response.code()})."
                }

            } catch (e: Exception) {

                Log.e(
                    "NEXUS_AI",
                    "PLANNER EXCEPTION",
                    e
                )

                plannerError =
                    "Tidak dapat terhubung ke NEXUS AI."

            } finally {

                plannerLoading = false
            }
        }
    }

    // =========================================================
    // REAL AI INSIGHTS
    // =========================================================

    fun generateInsights(tasks: List<TaskEntity>) {

        val signature = tasks
            .sortedBy { it.id }
            .joinToString("|") {
                "${it.id}:${it.title}:${it.category}:${it.time}:${it.completed}:${it.day}"
            }

        if (signature == lastInsightsSignature) {
            return
        }

        lastInsightsSignature = signature

        insightsJob?.cancel()

        insightsLoading = true
        insightsError = null

        insightsJob = viewModelScope.launch {

            try {

                val requestTasks = tasks
                    .take(50)
                    .map {
                        AIInsightTaskRequest(
                            title = it.title,
                            category = it.category,
                            time = it.time,
                            completed = it.completed,
                            day = it.day
                        )
                    }

                Log.d(
                    "NEXUS_AI",
                    "Generating insights for ${requestTasks.size} tasks"
                )

                val response =
                    ApiClient.api.generateAIInsights(
                        AIInsightsRequest(
                            tasks = requestTasks
                        )
                    )

                Log.d(
                    "NEXUS_AI",
                    "INSIGHTS HTTP CODE: ${response.code()}"
                )

                if (response.isSuccessful) {

                    val body = response.body()

                    if (body == null || body.insights.isEmpty()) {

                        insightsError =
                            "Nexus AI belum bisa menganalisis data."

                        insights = emptyList()

                    } else {

                        insights = body.insights.map {

                            AIInsightCard(
                                title = it.title.trim(),
                                value = it.value.trim(),
                                description = it.description.trim()
                            )
                        }

                        Log.d(
                            "NEXUS_AI",
                            "Generated ${insights.size} insights"
                        )
                    }

                } else {

                    val errorBody =
                        response.errorBody()?.string()

                    Log.e(
                        "NEXUS_AI",
                        "INSIGHTS ERROR: ${response.code()} $errorBody"
                    )

                    insightsError =
                        "AI Insights gagal (${response.code()})."
                }

            } catch (e: Exception) {

                Log.e(
                    "NEXUS_AI",
                    "INSIGHTS EXCEPTION",
                    e
                )

                insightsError =
                    "Tidak dapat terhubung ke NEXUS AI."

            } finally {

                insightsLoading = false
            }
        }
    }

    // =========================================================
    // CLEAR PLANNER
    // =========================================================

    fun clearPlan() {

        generatedPlan = emptyList()
        plannerGenerated = false
        plannerError = null
    }

    // =========================================================
    // REFRESH INSIGHTS
    // =========================================================

    fun refreshInsights() {

        lastInsightsSignature = null
    }
}